### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JadeTheGamer** [rsl140/Melvoridle-Auto-Manger#1]
**Describe the bug**
An error occurred while processing ticks:
Active Action: melvorD:Combat
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'checked')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'checked')
    at CombatManager.<anonymous> (blob:https://android.melvoridle.com/9f777319-3363-4c8a-a7a0-c12680dd4206:1:23166)
    at typeName.<computed> (https://android.melvoridle.com/assets/js/built/mod.js?5064:836:52)
    at CombatManager.checkDeath (https://android.melvoridle.com/assets/js/built/baseManager.js?5064:26:72)
    at Game.tick (https://android.melvoridle.com/assets/js/built/game.js?5064:177:148)
    at Game.runTicks (https://android.melvoridle.com/assets/js/built/game.js?5064:174:96)
    at Game.processTime (https://android.melvoridle.com/assets/js/built/game.js?5064:173:6)
    at Game.loop (https://android.melvoridle.com/assets/js/built/game.js?5064:194:50)
Current Equipment:
Helmet: melvorF:Air_Acolyte_Wizard_Hat
Platebody: melvorF:Air_Acolyte_Wizard_Robes
Platelegs: melvorF:Air_Acolyte_Wizard_Bottoms
Boots: melvorF:Air_Acolyte_Wizard_Boots
Weapon: melvorF:Staff_of_Earth
Amulet: melvorF:Jeweled_Necklace
Ring: melvorD:Gold_Topaz_Ring
Gloves: melvorD:Steel_Gloves
Quiver: melvorD:Iron_Arrows
Summon1: melvorF:Summoning_Familiar_Golbin_Thief

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WaterStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
Item: melvorD:Sardine, Qty: 8
Item: melvorD:Beef, Qty: 118
Item: melvorD:Herring, Qty: 176
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorD:Seagull
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: melvorD:Sandy_Shores
Modding Enabled. Loaded mods:
Dev
dbox
SEMI Core
Item Uses
Will I Die?
Shop Item Owned Indicator
SEMI Auto Loot
SEMI Drop Chances
SEMI Auto Farming
ETA
SEMI Auto Mine
SEMI Auto Eat
Township Breakdown
Kills in Combat
SEMI Auto Sell
SEMI Auto Bury
Time Skip
Quick Item/Bank Wiki
SEMI Save on Close
Reveal Thieving Loot
SEMI Auto Run
SEMI Auto Open
Rune Shop
SEMI XP Per Hour
AutoSort
SEMI Auto Collect Stockpiles
Do I have room?
Item Dashboard (MIID)
Buyable Dungeon Chests
Forgot My Hat
No Death Penalty
Thieving Stun Timer
Melvor Clicker
Additional Bank Buttons
Completion Log Icons
Mastery Token Shop
A Bit Cheating
One Click Farming
Reduced Monster Spawn Time Forked
XP in Sidebar
X  Auto Manger
Theatre of Blood
Add Items
Unlimited Offline
QuickShards
Better Auto Eat
Potion Seller (dbox Example)
TzHaar Fight Cave (Beta)
Bank Search Equipment Slots
SEMI Auto Bonfire

**To Reproduce**
1. Go to 'Combat'
2. Click on enemy type
3. Click to fight

**Expected behavior**
Normal combat action

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung Galazy A5 5G]
 - OS: [Android]
 - Browser [App]
 - Version [13]

**Additional context**

**Comment by rsl140** [comment]
fixed
