### ISSUE TITLE
Melvor Idle Major Update

### ISSUE THREAD

**Issue by maplecraft117** [rsl140/Melvoridle-Auto-Manger#2]
Melvor刚刚更新了重大版本1.3.x，这导致MOD X-Auto-Manager失效（或部分失效？），分类功能与修改器功能都无法运作，希望您能在百忙之中为该版本进行更新适配，不胜感激！

**Comment by rsl140** [comment]
临时处理了下 掉落那块 官方大改了 没法快速修复 暂时屏蔽了。其他功能已正常

**Comment by rsl140** [comment]
已修复
